# Generated by Django 4.2.1 on 2023-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('solution', models.TextField()),
                ('answer', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('topic', models.CharField(default='', max_length=100)),
                ('difficulty', models.IntegerField(default=0)),
                ('proofs', models.ImageField(upload_to='')),
            ],
        ),
    ]
