# Generated by Django 4.2.1 on 2023-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_url', models.CharField(max_length=250)),
                ('task_text', models.TextField()),
                ('solution', models.TextField()),
                ('level', models.CharField(max_length=15)),
                ('classes', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
