# Generated by Django 4.2.1 on 2023-10-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://img.freepik.com/premium-vector/avatar-profile-icon-vector-illustration_276184-165.jpg?size=338&ext=jpg&ga=GA1.1.386372595.1697760000&semt=ais', upload_to='profile_pics'),
        ),
    ]
