# Generated by Django 4.2.1 on 2023-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_profile_id_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='backend\\main\\profile_pics\x04914x3559_0xac120003_10815772101659466334.jpeg', upload_to='profile_pics'),
        ),
    ]
